accounts/urls.py
from django.urls import path, include
from accounts import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path("dashboard/", views.dashboard, name="dashboard"),
    path(
        "investigator_profile/", views.investigator_profile, name="investigator_profile"
    ),
    path("login/", views.investigator_login, name="login"),
    path("logout/", views.investigator_logout, name="logout"),
    path(
        "password_change/", views.investigator_password_change, name="password_change"
    ),
    path(
        "update_investigator_profile/",
        views.update_investigator_profile,
        name="update_investigator_profile",
    ),
    path(
        "add_investigator/",
        views.add_investigator,
        name="add_investigator",
    ),
    path(
        "investigators/",
        views.review_investigators,
        name="review_investigators",
    ),
    path("contact/", views.contact, name="contact"),
    path(
        "password_reset/", auth_views.PasswordResetView.as_view(), name="password_reset"
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
]

django_project/urls.py
"""
URL configuration for django_project project.
"""
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("accounts.urls")),
    path("", include("profiler.urls")),
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
]

profiler/urls.py
from django.urls import path
from profiler import views

app_name = "profiler"

urlpatterns = [
    path("criminal_profiles/", views.criminal_profiles, name="criminal_profiles"),
    path("criminal_profiles/add_profile/", views.add_profile, name="add_profile"),
    path(
        "criminal_profiles/profile/<int:criminal_id>/",
        views.view_profile,
        name="view_profile",
    ),
    path("criminal_profiles/match/", views.match_profile, name="match_profile"),
    path(
        "criminal_profiles/match/results/<int:match_id>/",
        views.match_results,
        name="match_results",
    ),
    path("search/", views.search, name="search"),
    path(
        "generate_results_pdf/<int:match_id>/",
        views.generate_results_pdf,
        name="generate_results_pdf",
    ),
]

profiler/models.py
from django.db import models
from django_countries.fields import CountryField
from django.core.validators import MinValueValidator, MaxValueValidator
from accounts.models import Investigator
from django.utils.text import slugify
from django.utils import timezone

class HackerClassification(models.TextChoices):
    BLACK_HAT = "BH", "Black Hat"
    GREY_HAT = "GH", "Grey Hat"
    SCRIPT_KIDDIE = "SK", "Script Kiddie"
    HACKTIVIST = "HA", "Hacktivist"
    STATE_SPONSORED = "SS", "State-Sponsored"
    CYBER_TERRORIST = "CT," "Cyber-Terrorist"
    MALICIOUS_INSIDER = "MI", "Malicious Insider"


class CyberCriminal(models.Model):
    investigator = models.ForeignKey(
        "accounts.Investigator", on_delete=models.CASCADE, null=True, blank=True
    )
    name = models.CharField(
        max_length=255,
        help_text="Middle name/s should be entered in full and not be represented by an initial",
        null=True,
        blank=True,
    )
    d_o_b = models.DateField(null=True, blank=True)
    nationality = models.CharField(
        null=True,
        blank=True,
        max_length=200,
        choices=CountryField().choices + [("", "Select Country")],
    )

    last_known_location = models.CharField(
        max_length=200,
        null=True,
        blank=True,
        choices=CountryField().choices + [("", "Select Country")],
    )
    hacker_classification = models.CharField(
        max_length=20,
        choices=HackerClassification.choices,
        default=HackerClassification.BLACK_HAT,
    )
    tactics = models.ManyToManyField(
        "Tactic", related_name="criminal_profiles", blank=True
    )
    techniques = models.ManyToManyField(
        "Technique", related_name="criminal_profiles", blank=True
    )
    manifesto = models.TextField(null=True, blank=True)

    height = models.PositiveIntegerField(
        help_text="Height in centimeters", null=True, blank=True
    )
    weight = models.PositiveIntegerField(
        help_text="Weight in kilograms", null=True, blank=True
    )
    hair_color = models.CharField(max_length=255, null=True, blank=True)
    eye_color = models.CharField(max_length=255, null=True, blank=True)

    aggression_level = models.IntegerField(
        help_text="Aggression level on a scale of 1-10",
        validators=[MinValueValidator(1), MaxValueValidator(10)],
        default=5,
    )
    risk_taking_level = models.IntegerField(
        help_text="Risk-taking level on a scale of 1-10",
        validators=[MinValueValidator(1), MaxValueValidator(10)],
        default=5,
    )

    def __str__(self):
        return f"{self.name}"

    class Meta:
        verbose_name_plural = "Cyber Criminals"
        ordering = ["investigator", "name"]


class Technique(models.Model):
    name = models.CharField(max_length=255)
    tactic = models.ForeignKey("Tactic", on_delete=models.CASCADE, null=True)
    description = models.TextField()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Techniques"
        unique_together = ["name", "tactic"]
        ordering = ["name"]


class Tactic(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(unique=True, null=True, blank=True)
    description = models.TextField()

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Tactic, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = "Tactics"


class AssociatedDevice(models.Model):
    cyber_criminal = models.ForeignKey(
        CyberCriminal,
        on_delete=models.CASCADE,
        related_name="associated_devices",
        null=True,
    )
    device_name = models.CharField(max_length=255)

    def __str__(self):
        return self.device_name

    class Meta:
        verbose_name_plural = "Associated Devices"


class AssociatedIP(models.Model):
    cyber_criminal = models.ForeignKey(
        CyberCriminal,
        on_delete=models.CASCADE,
        related_name="associated_ips",
        null=True,
    )
    ip_address = models.GenericIPAddressField()

    def __str__(self):
        return self.ip_address

    class Meta:
        verbose_name_plural = "Associated IPs"


class Alias(models.Model):
    cyber_criminal = models.ForeignKey(
        CyberCriminal,
        on_delete=models.CASCADE,
        related_name="aliases",
    )

    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Aliases"


class CyberCriminalMatch(models.Model):
    made_by = models.ForeignKey(
        "accounts.Investigator", on_delete=models.CASCADE, null=True
    )
    techniques = models.ManyToManyField("Technique", related_name="matches", blank=True)
    matched_criminals = models.ManyToManyField(
        "CyberCriminal", related_name="matches", blank=True
    )
    matched_on = models.DateTimeField(default=timezone.now)
    def __str__(self):
        return f"{self.made_by}'s Cyber Criminal Match"

    class Meta:
        verbose_name_plural = "Cyber Criminal Matches"
        ordering = ["made_by"]

profiler/views.py
from django.contrib import messages
from django.db.models import Count, Q
from django.http import FileResponse, HttpResponse
from django.shortcuts import redirect, render
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.pdfgen import canvas
from reportlab.platypus import Paragraph, SimpleDocTemplate, Table, TableStyle

from accounts.decorators import investigator_required
from profiler.matcher import match_criminal, match_projected_techniques

from .forms import CyberCriminalForm
from .models import (
    Alias,
    AssociatedDevice,
    AssociatedIP,
    CyberCriminal,
    CyberCriminalMatch,
    Technique,
)


@investigator_required
def view_profile(request, criminal_id):
    cyber_criminal = CyberCriminal.objects.get(id=criminal_id)

    context = {
        "cyber_criminal": cyber_criminal,
    }
    template_name = "profiler/view_profile.html"
    return render(request, template_name, context)


@investigator_required
def add_profile(request):
    techniques = Technique.objects.all()

    if request.method != "POST":
        criminal_form = CyberCriminalForm()
    else:
        criminal_form = CyberCriminalForm(request.POST)
        aliases = request.POST.get("aliases", "")
        alias_list = [alias.strip() for alias in aliases.split(",")]
        associated_ips = request.POST.get("ips", "")
        ip_list = [ip.strip() for ip in associated_ips.split(",")]
        associated_devices = request.POST.get("devices", "")
        device_list = [device.strip() for device in associated_devices.split(",")]
        techniques_used = request.POST.getlist("techniques")

        if criminal_form.is_valid():
            cyber_criminal = criminal_form.save(commit=False)
            cyber_criminal.investigator = request.user
            cyber_criminal.save()

            for alias in alias_list:
                Alias.objects.create(cyber_criminal=cyber_criminal, name=alias)

            for ip in ip_list:
                AssociatedIP.objects.create(
                    cyber_criminal=cyber_criminal, ip_address=ip
                )

            for device in device_list:
                AssociatedDevice.objects.create(
                    cyber_criminal=cyber_criminal, device_name=device
                )

            tactics = set()

            for technique in set(techniques_used):
                new_technique = Technique.objects.get(id=technique)
                cyber_criminal.techniques.add(new_technique)
                tactics.add(new_technique.tactic)

            for tactic in tactics:
                cyber_criminal.tactics.add(tactic)

            messages.success(
                request,
                f"Criminal Profile for {cyber_criminal.name} created successfully.",
            )
            return redirect("profiler:criminal_profiles")

    context = {
        "criminal_form": criminal_form,
        "techniques": techniques,
    }
    template_name = "profiler/add_profile.html"
    return render(request, template_name, context)


@investigator_required
def criminal_profiles(request):
    cyber_criminals = CyberCriminal.objects.all()

    context = {"cyber_criminals": cyber_criminals}
    tempate_name = "profiler/cyber_criminals.html"
    return render(request, tempate_name, context)


@investigator_required
def match_profile(request):
    cyber_criminals = CyberCriminal.objects.all()
    techniques = Technique.objects.all()

    if request.method != "POST":
        criminal_form = CyberCriminalForm()
    else:
        criminal_form = CyberCriminalForm(request.POST)
        aliases = request.POST.get("aliases", "")
        alias_list = [alias.strip() for alias in aliases.split(",")]
        associated_ips = request.POST.get("ips", "")
        ip_list = [ip.strip() for ip in associated_ips.split(",")]
        associated_devices = request.POST.get("devices", "")
        device_list = [device.strip() for device in associated_devices.split(",")]
        techniques_used = request.POST.getlist("techniques")

        if criminal_form.is_valid():
            temp_criminal = criminal_form.save(commit=False)
            temp_criminal.investigator = request.user
            temp_criminal.save()

            for alias in alias_list:
                Alias.objects.create(cyber_criminal=temp_criminal, name=alias)

            # add ip only if ip is not empty
            if ip_list[0] != "":
                for ip in ip_list:
                    AssociatedIP.objects.create(
                        cyber_criminal=temp_criminal, ip_address=ip
                    )

            # add device only if device is not empty
            if device_list[0] != "":
                for device in device_list:
                    AssociatedDevice.objects.create(
                        cyber_criminal=temp_criminal, device_name=device
                    )

            tactics = set()
            temp_techniques = set()

            for technique in set(techniques_used):
                new_technique = Technique.objects.get(id=technique)
                temp_criminal.techniques.add(new_technique)
                temp_techniques.add(new_technique)
                tactics.add(new_technique.tactic)

            for tactic in tactics:
                temp_criminal.tactics.add(tactic)

            matched_criminals = match_criminal(temp_criminal)
            if matched_criminals is None:
                messages.info(
                    request,
                    f"No matching criminal profiles found for {temp_criminal.name}.",
                )
                return redirect("profiler:criminal_profiles")
            else:
                possible_techniques = match_projected_techniques(
                    temp_criminal, matched_criminals
                )

                temp_criminal.delete()

                cyber_criminal_match = CyberCriminalMatch.objects.create(
                    made_by=request.user,
                )

                matched_criminals_list = []
                for criminal, _ in matched_criminals:
                    matched_criminals_list.append(criminal.id)

                cyber_criminal_match.matched_criminals.set(matched_criminals_list)
                cyber_criminal_match.techniques.set(possible_techniques)
                cyber_criminal_match.save()

                messages.success(
                    request,
                    f"Matching criminal profiles found",
                )
                return redirect(
                    "profiler:match_results", match_id=cyber_criminal_match.id
                )

    context = {
        "cyber_criminals": cyber_criminals,
        "techniques": techniques,
        "criminal_form": criminal_form,
    }
    tempate_name = "profiler/match_profile.html"
    return render(request, tempate_name, context)


@investigator_required
def match_results(request, match_id):
    cyber_criminal_match = CyberCriminalMatch.objects.get(id=match_id)

    matched_criminals = cyber_criminal_match.matched_criminals.all()
    possible_techniques = cyber_criminal_match.techniques.all()

    context = {
        "match": cyber_criminal_match,
        "matched_criminals": matched_criminals,
        "possible_techniques": possible_techniques,
    }
    template_name = "profiler/match_results.html"
    return render(request, template_name, context)


@investigator_required
def search(request):
    query = request.GET.get("q")

    cyber_criminals = CyberCriminal.objects.filter(
        Q(name__icontains=query)
        | Q(techniques__name__icontains=query)
        | Q(tactics__name__icontains=query)
        | Q(aliases__name__icontains=query)
        | Q(associated_ips__ip_address__icontains=query)
        | Q(associated_devices__device_name__icontains=query)
    ).distinct()

    context = {
        "cyber_criminals": cyber_criminals,
    }
    template_name = "profiler/search.html"
    return render(request, template_name, context)


@investigator_required
def generate_results_pdf(request, match_id):
    match = CyberCriminalMatch.objects.get(id=match_id)

    # Create a FileResponse object with the appropriate PDF headers.
    response = HttpResponse(content_type="application/pdf")
    response["Content-Disposition"] = (
        f"attachment; filename=Match by {match.made_by} on {match.matched_on.strftime('%Y-%m-%d %H:%M:%S')} Report.pdf"
    )

    # Create the PDF object, using the response object as its "file".
    p = SimpleDocTemplate(response, pagesize=letter)

    # Prepare data for the table
    data = [["Name", "Description"]]
    styles = getSampleStyleSheet()
    for technique in match.techniques.all():
        name = Paragraph(technique.name, styles["BodyText"])
        description = Paragraph(technique.description, styles["BodyText"])
        data.append([name, description])

    # Calculate the available width of the page
    available_width = letter[0] - 2 * 20  # assuming a margin of 20 on each side

    # Create a Table with the data and add it to the PDF
    table = Table(data, colWidths=[available_width / 2, available_width / 2])
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.grey),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
                ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, 0), 14),
                ("BOTTOMPADDING", (0, 0), (-1, 0), 12),
                ("BACKGROUND", (0, 1), (-1, -1), colors.beige),
                ("GRID", (0, 0), (-1, -1), 1, colors.black),
                ("LEFTPADDING", (0, 0), (-1, -1), 5),
                ("RIGHTPADDING", (0, 0), (-1, -1), 5),
                ("TOPPADDING", (0, 0), (-1, -1), 5),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ]
        )
    )
    styles["Title"].fontSize = 23

templates/profiler/cyber_criminal_modal.html
<!-- Modal -->
<div class="modal modal-lg fade" id="cyberCriminalModal{{cyber_criminal.id}}" data-bs-keyboard="false" tabindex="-1"
    aria-labelledby="cyberCriminalModal{{cyber_criminal.id}}Label" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title display-5" id="cyberCriminalModal{{cyber_criminal.id}}Label">
                    {{cyber_criminal.name }}</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <section class="container-fluid">
                    <div class="row">
                        <div class="col-md-4">
                            <div class="card">
                                <div class="card-body">
                                    <h5 class="card-title">Personal Information</h5>
                                    <p class="card-text">
                                        <strong>Date of Birth:&nbsp;</strong>
                                        {{cyber_criminal.d_o_b}}
                                    </p>
                                    <p class="card-text" id="nationality">
                                        <strong>Nationality:&nbsp;</strong>
                                        {{cyber_criminal.get_nationality_display}}
                                    </p>
                                    <p class="card-text" id="last_known_location">
                                        <strong>Last Known
                                            Location:&nbsp;</strong>
                                        {{cyber_criminal.get_last_known_location_display}}
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="card">
                                <div class="card-body">
                                    <h5 class="card-title">Physical Information</h5>
                                    <p class="card-text" id="height">
                                        <strong>Height:&nbsp;</strong>
                                        {{cyber_criminal.height}} cm
                                    </p>
                                    <p class="card-text" id="weight">
                                        <strong>Weight:&nbsp;</strong>
                                        {{cyber_criminal.weight}} kg
                                    </p>
                                    <p class="card-text" id="weight">
                                        <strong>Hair Color:&nbsp;</strong>
                                        {{cyber_criminal.hair_color}}
                                    </p>
                                    <p class="card-text" id="weight">
                                        <strong>Eye Color:&nbsp;</strong>
                                        {{cyber_criminal.eye_color}}
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="card">
                                <div class="card-body">
                                    <h5 class="card-title">Psychological Information</h5>
                                    <p class="card-text" id="aggression_level">
                                        <strong>Aggression Level:&nbsp;</strong>
                                        {{cyber_criminal.aggression_level}}/10
                                    </p>
                                    <p class="card-text" id="risk_taking_level">
                                        <strong>Risk-taking Level:&nbsp;</strong>
                                        {{cyber_criminal.risk_taking_level}}/10
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="card">
                                <div class="card-body">
                                    <h5 class="card-title">Technical Information</h5>
                                    <div class="row">
                                        <div class="col-md-6">
                                            <p class="card-text" id="hacker_classification">
                                                <strong>Hacker
                                                    Classification:&nbsp;</strong>{{cyber_criminal.get_hacker_classification_display}}
                                            </p>
                                            <p class="card-text" id="aliases">
                                                <strong>Aliases:&nbsp;</strong>
                                                {% for alias in cyber_criminal.aliases.all %}
                                                <small class="item-pill">{{ alias }}</small>
                                                {% endfor %}
                                            </p>
                                            <p class="card-text" id="associated_devices">
                                                <strong>Asssociated Devices:&nbsp;</strong>
                                                {% for device in cyber_criminal.associated_devices.all %}
                                                <small class="item-pill">{{ device }}</small>
                                                {% endfor %}
                                            </p>
                                            <p class="card-text" id="associated_ips">
                                                <strong>Associated IPs:&nbsp;</strong>
                                                {% for ip_adddress in cyber_criminal.associated_ips.all %}
                                                <small class="item-pill">{{ ip_adddress }}</small>
                                                {% endfor %}
                                            </p>
                                        </div>
                                        <div class="col-md-6">
                                            <p class="card-text" id="techniques">
                                                <strong>Techniques:&nbsp;</strong>
                                                {% for technique in cyber_criminal.techniques.all %}
                                                <small class="item-pill" data-bs-toggle="tooltip"
                                                    data-bs-placement="top" data-bs-custom-class="custom-tooltip"
                                                    data-bs-title="{{technique.description}}">
                                                    {{technique.name}}
                                                </small>
                                                {% endfor %}
                                            </p>
                                            <p class="card-text" id="tactics">
                                                <strong>Tactics:&nbsp;</strong>
                                                {% for tactic in cyber_criminal.tactics.all %}
                                                <small class="item-pill" data-bs-toggle="tooltip"
                                                    data-bs-placement="top" data-bs-custom-class="custom-tooltip"
                                                    data-bs-title="{{tactic.description}}">
                                                    {{tactic.name}}
                                                </small>
                                                {% endfor %}
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>
</div>

templates/profiler/cyber_criminals.html
{% extends 'base.html' %}

{% load django_bootstrap5 %}
{% load static %}

{% block title %}Cyber-Criminals{% endblock title %}

{% block header %}
<div class="pagetitle">
    <h1>List Cyber-Criminals</h1>
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'dashboard' %}">Home</a></li>
            <li class="breadcrumb-item active">Cyber-Criminals</li>
        </ol>
    </nav>
</div>
{% endblock header %}

{% block content %}
<section class="container-fluid">
    <table id="myTable" class="display">
        <thead>
            <tr>
                <th>Name</th>
                <th>D.O.B</th>
                <th>Nationality</th>
                <th>Aggression Level</th>
            </tr>
        </thead>
        <tbody>
            {% for cyber_criminal in cyber_criminals %}
            <tr>
                <td>
                    <a href="{% url 'profiler:view_profile' cyber_criminal.id %}">
                        {{ cyber_criminal.name }}
                    </a>
                </td>
                <td>{{ cyber_criminal.d_o_b }}</td>
                <td>{{ cyber_criminal.get_nationality_display }}</td>
                <td>{{ cyber_criminal.aggression_level }}/10</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</section>
{% endblock content %}

{% block custom_js %}
<script>
    $('#myTable').DataTable({
        dom: 'Bfrtip',
        buttons: [
            'copy', 'csv', 'excel', 'pdf', 'print'
        ]
    });
</script>
{% endblock custom_js %}

templates/profiler/match_results.html
{% extends 'base.html' %}

{% load django_bootstrap5 %}
{% load static %}

{% block title %}Cyber-Criminals{% endblock title %}

{% block custom_css %}
<style>
    .item-pill {
        background-color: #cfe3f3;
        border: none;
        color: black;
        padding: 3px 5px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        margin: 4px 2px;
        cursor: default;
        border-radius: 16px;
        font-weight: 500;
    }

    .item-pill:hover {
        background-color: #dee9f1;
    }
</style>
{% endblock custom_css %}

{% block header %}
<div class="pagetitle">
    <h1>Criminal Profile Match Results</h1>
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'dashboard' %}">Home</a></li>
            <li class="breadcrumb-item"><a href="{% url 'profiler:criminal_profiles' %}">Cyber-Criminals</a></li>
            <li class="breadcrumb-item"><a href="{% url 'profiler:match_profile' %}">Match</a></li>
            <li class="breadcrumb-item active">Match Results</li>
        </ol>
    </nav>
</div>
{% endblock header %}

{% block content %}
<div class="d-flex justify-content-end">
    <a class="btn btn-success" href="{% url 'profiler:generate_results_pdf' match.id %}">Generate Report</a>
</div>

<section>
    <div class="m-3 px-3">
        <h2>Top 3 Matched Profiles</h2>
        <p class="text-muted small">
            Below are the top 3 profiles that match your search criteria. Click on each profile to obtain a view a
            comprehensive overview of the cyber-criminal activities and capabilities.
        </p>
        <div class="row">
            {% for cyber_criminal in matched_criminals %}
            <div class="col">
                <button class="card" type="button" data-bs-toggle="modal"
                    data-bs-target="#cyberCriminalModal{{cyber_criminal.id}}">
                    <div class="card-body">
                        <h5 class="card-title">{{ cyber_criminal.name }}</h5>
                        <p class="card-text" id="aliases">
                            <strong>Aliases:&nbsp;</strong>
                            {% for alias in cyber_criminal.aliases.all %}
                            <small class="item-pill">{{ alias }}</small>
                            {% endfor %}
                        </p>
                    </div>
                </button>
            </div>

            <!-- Modal -->
            {% include 'profiler/cyber_criminal_modal.html' %}
            <!-- End of Modal  -->

            {% empty %}
            <p class="small text-warning">
                We're sorry, but no profiles matched your search criteria. Please try again with different parameters.
            </p>
            {% endfor %}
        </div>

    </div>
    <div class="card p-3">
        <h2>List of Matching Techniques</h2>
        <p>
            Based on the information provided, the following techniques are the most likely to have been used or be used
            by the criminal in the future. This information can be used to further refine your search criteria.
        </p>
        <p class="card-text" id="techniques">
            <strong>Techniques:&nbsp;</strong>
            {% for technique in possible_techniques %}
            <span class="item-pill small" data-bs-toggle="tooltip" data-bs-placement="top"
                data-bs-custom-class="custom-tooltip" data-bs-title="{{technique.description}}">
                {{technique.name}}
            </span>
            {% endfor %}
        </p>
    </div>
</section>
{% endblock content %}

{% block custom_js %}
{% endblock custom_js %}