accounts/urls.py
from django.urls import path, include
from accounts import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path("dashboard/", views.dashboard, name="dashboard"),
    path(
        "investigator_profile/", views.investigator_profile, name="investigator_profile"
    ),
    path("login/", views.investigator_login, name="login"),
    path("logout/", views.investigator_logout, name="logout"),
    path(
        "password_change/", views.investigator_password_change, name="password_change"
    ),
    path(
        "update_investigator_profile/",
        views.update_investigator_profile,
        name="update_investigator_profile",
    ),
    path(
        "add_investigator/",
        views.add_investigator,
        name="add_investigator",
    ),
    path(
        "investigators/",
        views.review_investigators,
        name="review_investigators",
    ),
    path("contact/", views.contact, name="contact"),
    path(
        "password_reset/", auth_views.PasswordResetView.as_view(), name="password_reset"
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
]

django_project/urls.py
"""
URL configuration for django_project project.
"""
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("accounts.urls")),
    path("", include("profiler.urls")),
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
]

profiler/urls.py
from django.urls import path
from profiler import views

app_name = "profiler"

urlpatterns = [
    path("criminal_profiles/", views.criminal_profiles, name="criminal_profiles"),
    path("criminal_profiles/add_profile/", views.add_profile, name="add_profile"),
    path(
        "criminal_profiles/profile/<int:criminal_id>/",
        views.view_profile,
        name="view_profile",
    ),
    path("criminal_profiles/match/", views.match_profile, name="match_profile"),
    path(
        "criminal_profiles/match/results/<int:match_id>/",
        views.match_results,
        name="match_results",
    ),
    path("search/", views.search, name="search"),
    path(
        "generate_results_pdf/<int:match_id>/",
        views.generate_results_pdf,
        name="generate_results_pdf",
    ),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, UserManager
from django.utils import timezone


class ContactType(models.TextChoices):
    INVESTIGATOR = "INV", "Investigator"
    GUEST = "GST", "Guest"


class AdminInvestigatorManager(UserManager):
    """Custom Admin Investigator Manager"""

    def get_queryset(self):
        return (
            super()
            .get_queryset()
            .filter(investigator_type=Investigator.InvestigatorType.ADMIN)
        )


class InvestigatorManager(UserManager):
    """Custom Investigator Manager"""

    def get_queryset(self):
        return (
            super()
            .get_queryset()
            .filter(investigator_type=Investigator.InvestigatorType.INVESTIGATOR)
        )


class Investigator(AbstractUser):
    """
    The model for a forensic investigator.
    """

    class InvestigatorType(models.TextChoices):
        INVESTIGATOR = "INV", "Investigator"
        ADMIN = "ADM", "Admin Investigator"

    # The investigator's phone number.
    phone = models.CharField(max_length=20, blank=False, unique=True)
    # The investigator's address.
    address = models.CharField(max_length=200, blank=False)
    investigator_type = models.CharField(
        max_length=3,
        choices=InvestigatorType.choices,
        default=InvestigatorType.INVESTIGATOR,
    )

    # The default manager.
    objects = UserManager()
    # The admin investigator users manager.
    admin_investigator_objects = AdminInvestigatorManager()
    # The investigator users manager.
    investigator_objects = InvestigatorManager()

    @property
    def is_investigator(self):
        return self.investigator_type == self.InvestigatorType.INVESTIGATOR

    @property
    def is_admin_investigator(self):
        return self.investigator_type == self.InvestigatorType.ADMIN

    @property
    def completion_percentage(self):
        # Define the fields to be checked for completion
        profile_fields = [
            self.first_name,
            self.last_name,
            self.email,
            self.phone,
            self.address,
        ]
        # Calculate the number of completed fields
        completed_fields = sum(1 for field in profile_fields if field)

        # Calculate the percentage of completion
        if len(profile_fields) > 0:
            completion_percentage = (completed_fields / len(profile_fields)) * 100
        else:
            completion_percentage = (
                100  # Profile is considered complete if there are no fields to complete
            )

        return int(completion_percentage)

    class Meta:
        verbose_name = "Investigator"
        verbose_name_plural = "Investigators"
        ordering = ["username"]


class Contact(models.Model):
    name = models.CharField(max_length=255, blank=True, null=True)
    email = models.EmailField(null=True, blank=True)
    subject = models.CharField(max_length=255)
    message = models.TextField()
    created_at = models.DateTimeField(default=timezone.now)
    contact_type = models.CharField(
        max_length=3,
        choices=ContactType.choices,
        default=ContactType.GUEST,
    )

    def __str__(self):
        return f"{self.name} - {self.subject[:50]}..."

    class Meta:
        verbose_name = "Contact"
        verbose_name_plural = "Contacts"
        ordering = ["created_at"]

profiler/models.py
from django.db import models
from django_countries.fields import CountryField
from django.core.validators import MinValueValidator, MaxValueValidator
from accounts.models import Investigator
from django.utils.text import slugify
from django.utils import timezone

class HackerClassification(models.TextChoices):
    BLACK_HAT = "BH", "Black Hat"
    GREY_HAT = "GH", "Grey Hat"
    SCRIPT_KIDDIE = "SK", "Script Kiddie"
    HACKTIVIST = "HA", "Hacktivist"
    STATE_SPONSORED = "SS", "State-Sponsored"
    CYBER_TERRORIST = "CT," "Cyber-Terrorist"
    MALICIOUS_INSIDER = "MI", "Malicious Insider"


class CyberCriminal(models.Model):
    investigator = models.ForeignKey(
        "accounts.Investigator", on_delete=models.CASCADE, null=True, blank=True
    )
    name = models.CharField(
        max_length=255,
        help_text="Middle name/s should be entered in full and not be represented by an initial",
        null=True,
        blank=True,
    )
    d_o_b = models.DateField(null=True, blank=True)
    nationality = models.CharField(
        null=True,
        blank=True,
        max_length=200,
        choices=CountryField().choices + [("", "Select Country")],
    )

    last_known_location = models.CharField(
        max_length=200,
        null=True,
        blank=True,
        choices=CountryField().choices + [("", "Select Country")],
    )
    hacker_classification = models.CharField(
        max_length=20,
        choices=HackerClassification.choices,
        default=HackerClassification.BLACK_HAT,
    )
    tactics = models.ManyToManyField(
        "Tactic", related_name="criminal_profiles", blank=True
    )
    techniques = models.ManyToManyField(
        "Technique", related_name="criminal_profiles", blank=True
    )
    manifesto = models.TextField(null=True, blank=True)

    height = models.PositiveIntegerField(
        help_text="Height in centimeters", null=True, blank=True
    )
    weight = models.PositiveIntegerField(
        help_text="Weight in kilograms", null=True, blank=True
    )
    hair_color = models.CharField(max_length=255, null=True, blank=True)
    eye_color = models.CharField(max_length=255, null=True, blank=True)

    aggression_level = models.IntegerField(
        help_text="Aggression level on a scale of 1-10",
        validators=[MinValueValidator(1), MaxValueValidator(10)],
        default=5,
    )
    risk_taking_level = models.IntegerField(
        help_text="Risk-taking level on a scale of 1-10",
        validators=[MinValueValidator(1), MaxValueValidator(10)],
        default=5,
    )

    def __str__(self):
        return f"{self.name}"

    class Meta:
        verbose_name_plural = "Cyber Criminals"
        ordering = ["investigator", "name"]


class Technique(models.Model):
    name = models.CharField(max_length=255)
    tactic = models.ForeignKey("Tactic", on_delete=models.CASCADE, null=True)
    description = models.TextField()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Techniques"
        unique_together = ["name", "tactic"]
        ordering = ["name"]


class Tactic(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(unique=True, null=True, blank=True)
    description = models.TextField()

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Tactic, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = "Tactics"


class AssociatedDevice(models.Model):
    cyber_criminal = models.ForeignKey(
        CyberCriminal,
        on_delete=models.CASCADE,
        related_name="associated_devices",
        null=True,
    )
    device_name = models.CharField(max_length=255)

    def __str__(self):
        return self.device_name

    class Meta:
        verbose_name_plural = "Associated Devices"


class AssociatedIP(models.Model):
    cyber_criminal = models.ForeignKey(
        CyberCriminal,
        on_delete=models.CASCADE,
        related_name="associated_ips",
        null=True,
    )
    ip_address = models.GenericIPAddressField()

    def __str__(self):
        return self.ip_address

    class Meta:
        verbose_name_plural = "Associated IPs"


class Alias(models.Model):
    cyber_criminal = models.ForeignKey(
        CyberCriminal,
        on_delete=models.CASCADE,
        related_name="aliases",
    )

    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Aliases"


class CyberCriminalMatch(models.Model):
    made_by = models.ForeignKey(
        "accounts.Investigator", on_delete=models.CASCADE, null=True
    )
    techniques = models.ManyToManyField("Technique", related_name="matches", blank=True)
    matched_criminals = models.ManyToManyField(
        "CyberCriminal", related_name="matches", blank=True
    )
    matched_on = models.DateTimeField(default=timezone.now)
    def __str__(self):
        return f"{self.made_by}'s Cyber Criminal Match"

    class Meta:
        verbose_name_plural = "Cyber Criminal Matches"
        ordering = ["made_by"]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>{% block title %}Cyber-Criminal Profiling{% endblock title %}</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="{% static 'assets/img/favicon.png' %}" rel="icon">
    <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link
        href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
        rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/quill/quill.snow.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/quill/quill.bubble.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/simple-datatables/style.css' %}" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/sweetalert2@11.7.32/dist/sweetalert2.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.7.32/dist/sweetalert2.all.min.js"></script>

    <!-- jquery -->
    <script src="https://code.jquery.com/jquery-3.7.1.js"
        integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>

    <!-- datatables -->
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.8/css/jquery.dataTables.min.css">
    <script src="https://cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js"></script>
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.4.2/css/buttons.dataTables.min.css">
    <script src="https://cdn.datatables.net/buttons/2.4.2/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.4.2/js/buttons.colVis.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.4.2/js/buttons.print.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.4.2/js/buttons.html5.min.js"></script>
    <link rel="stylesheet" href="https://cdn.datatables.net/colreorder/1.7.0/css/colReorder.dataTables.min.css">
    <script src="https://cdn.datatables.net/colreorder/1.7.0/js/dataTables.colReorder.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    
    <!-- Template Main CSS File -->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

    <!-- fontawesome cdn -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
        integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/js/all.min.js"
        integrity="sha512-GWzVrcGlo0TxTRvz9ttioyYJ+Wwk9Ck0G81D+eO63BaqHaJ3YZX9wuqjwgfcV/MrB2PhaVX9DkYVhbFpStnqpQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    {% block custom_css %}

    {% endblock custom_css %}
</head>

<body>

    {% if user.is_authenticated %}
    <!-- ======= Header ======= -->
    <header id="header" class="header fixed-top d-flex align-items-center">

        <div class="d-flex align-items-center justify-content-between">
            <a href="{% url 'home' %}" class="logo d-flex align-items-center">
                <img class="m-0" src="{% static 'assets/img/logo.png' %}" alt="">
                <span class="d-none d-lg-block">Cyber-Criminal Profiling System</span>
            </a>
            <i class="bi bi-list toggle-sidebar-btn"></i>
        </div><!-- End Logo -->

        <div class="search-bar">
            <form class="search-form d-flex align-items-center" method="get" action="{% url 'profiler:search' %}">
                <input type="text" name="q" placeholder="Search" title="Enter search keyword">
                <button type="submit" title="Search"><i class="bi bi-search"></i></button>
            </form>
        </div>

        <nav class="header-nav ms-auto">
            <ul class="d-flex align-items-center">

                <li class="nav-item d-block d-lg-none">
                    <a class="nav-link nav-icon search-bar-toggle " href="#">
                        <i class="bi bi-search"></i>
                    </a>
                </li>

                <li class="nav-item dropdown pe-3">

                    <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
                        <img src="{% static 'assets/img/user.jpg' %}" alt="Profile" class="rounded-circle">
                        <span class="d-none d-md-block dropdown-toggle ps-2">{{user.first_name|slice:":1"}}.
                            {{user.last_name}}</span>
                    </a><!-- End Profile Image Icon -->

                    <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
                        <li class="dropdown-header">
                            <h6>{{ user.get_full_name }}</h6>
                            <span>{{ user.get_investigator_type_display }}</span>
                        </li>

                        <li>
                            <hr class="dropdown-divider">
                        </li>

                        <li>
                            <a class="dropdown-item d-flex align-items-center" href="{% url 'investigator_profile' %}">
                                <i class="bi bi-gear"></i>
                                <span>Account Settings</span>
                            </a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li>
                            <button class="dropdown-item d-flex align-items-center" onclick="confirmLogout()">
                                <i class="bi bi-box-arrow-right"></i>
                                <span>Sign Out</span>
                            </button>
                        </li>

                    </ul><!-- End Profile Dropdown Items -->
                </li><!-- End Profile Nav -->

            </ul>
        </nav><!-- End Icons Navigation -->

    </header><!-- End Header -->

    <!-- ======= Sidebar ======= -->
    <aside id="sidebar" class="sidebar">

        <ul class="sidebar-nav" id="sidebar-nav">

            <li class="nav-item">
                <a class="nav-link" href="{% url 'dashboard' %}">
                    <i class="bi bi-grid"></i>
                    <span>Dashboard</span>
                </a>
            </li>

            {% if user.is_admin_investigator %}
            <li class="nav-heading">Investigators</li>

            <li class="nav-item">
                <a class="nav-link collapsed" href="{% url 'add_investigator' %}">
                    <i class="bi bi-person-plus"></i>
                    <span>Add Investigator</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link collapsed" href="{% url 'review_investigators' %}">
                    <i class="bi bi-people"></i>
                    <span>Review Investigators</span>
                </a>
            </li>
            {% endif %}

            <li class="nav-heading">Cyber-Criminals</li>

            <li class="nav-item">
                <a class="nav-link collapsed" href="{% url 'profiler:add_profile' %}">
                    <i class="bi bi-upload"></i>
                    <span>Add Profile</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link collapsed" href="{% url 'profiler:criminal_profiles' %}">
                    <i class="bi bi-book"></i>
                    <span>Review Profiles</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link collapsed" href="{% url 'profiler:match_profile' %}">
                    <i class="bx bx-fingerprint"></i>
                    <span>Match Profile</span>
                </a>
            </li>

            <li class="nav-heading">Help</li>

            <li class="nav-item">
                <a class="nav-link collapsed" href="{% url 'contact' %}">
                    <i class="bi bi-envelope"></i>
                    <span>Contact</span>
                </a>
            </li>
        </ul>

    </aside><!-- End Sidebar-->

    {% endif %}
    {% if messages %}
    {% for message in messages %}
    {% if message.tags == 'success' %}
    <script>
        var message = "{{ message|safe }}";
        var alertType = "success";
        console.log(message);

        Swal.fire({
            title: "Success!",
            text: message,
            icon: "success"
        });
    </script>
    {% elif message.tags == 'info' %}
    <script>
        var message = "{{ message|safe }}";
        var alertType = "info";
        console.log(message);

        Swal.fire({
            title: "info!",
            text: message,
            icon: "info"
        });

    </script>

    {% elif message.tags == 'warning' %}
    <script>
        var message = "{{ message|safe }}";
        var alertType = "warning";
        console.log(message);

        Swal.fire({
            title: "Warning!",
            text: message,
            icon: "warning"
        });
    </script>

    {% elif message.tags == 'error' %}
    <script>
        var message = "{{ message|safe }}";
        var alertType = "error";
        console.log(message);

        Swal.fire({
            title: "Error!",
            text: message,
            icon: "error"
        });
    </script>

    {% endif %}
    {% endfor %}
    {% endif %}

    <main id="main" class="main">

        {% block header %}

        {% endblock header %}

        {% block content %}

        {% endblock content %}

    </main><!-- End #main -->

    <!-- ======= Footer ======= -->
    <footer id="footer" class="footer">
        <div class="copyright">
            &copy; Copyright <strong><span>Cyber-Criminal Profiling System</span></strong>. All Rights Reserved
        </div>
    </footer><!-- End Footer -->

    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
            class="bi bi-arrow-up-short"></i></a>

    <!-- Vendor JS Files -->
    <script src="{% static 'assets/vendor/apexcharts/apexcharts.min.js' %}"></script>
    <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/vendor/chart.js/chart.umd.js' %}"></script>
    <script src="{% static 'assets/vendor/echarts/echarts.min.js' %}"></script>
    <script src="{% static 'assets/vendor/quill/quill.min.js' %}"></script>
    <script src="{% static 'assets/vendor/simple-datatables/simple-datatables.js' %}"></script>
    <script src="{% static 'assets/vendor/tinymce/tinymce.min.js' %}"></script>
    <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

    <!-- Template Main JS File -->
    <script src="{% static 'assets/js/main.js' %}"></script>
    <script>
        function confirmLogout() {
            Swal.fire({
                title: "Warning!",
                text: "Are you sure you want to log out?",
                icon: "warning",
                confirmButtonText: "Log Me Out",
                confirmButtonColor: "#d33",
            }).then((result) => {
                if (result.isConfirmed) {
                    window.location.href = "{% url 'logout' %}";
                }
            })
        }
    </script>
    {% block custom_js %}
    {% endblock custom_js %}

</body>

</html>

templates/dashboard.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Dashboard{% endblock title %}


{% block header %}
<div class="pagetitle">
    <h1>Dashboard</h1>
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'dashboard' %}">Home</a></li>
            <li class="breadcrumb-item active">Dashboard</li>
        </ol>
    </nav>
</div>
{% endblock header %}

{% block content %}
<section class="section dashboard">
    <!-- Left side columns -->
    <div class="col-lg-12">
        <div class="row">

            <!-- Sales Card -->
            <div class="col-xxl-4 col-md-4">
                <div class="card info-card sales-card">
                    <div class="card-body">
                        <div class="d-flex align-items-center my-4">
                            <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
                                <i class="bi bi-person"></i>
                            </div>
                            <div class="ps-1">
                                <h6>Profile</h6>
                                <span class="text-success small pt-1 fw-bold">
                                    {{request.user.completion_percentage}}%
                                </span>
                                <span class="text-muted small pt-2 ps-1">complete</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Revenue Card -->
            <div class="col-xxl-4 col-md-4">
                <div class="card info-card revenue-card">
                    <div class="card-body">
                        <div class="d-flex align-items-center my-4">
                            <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
                                <i class="bi bi-search"></i>
                            </div>
                            <div class="ps-1">
                                <h6>&nbsp;&nbsp;&nbsp;{{investigators.count}}</h6>
                                <span class="text-muted small pt-2 ps-1">Investigators</span>
                            </div>
                        </div>
                    </div>

                </div>
            </div><!-- End Revenue Card -->

            <!-- Customers Card -->
            <div class="col-xxl-4 col-md-4">
                <div class="card info-card customers-card">
                    <div class="card-body">
                        <div class="d-flex align-items-center my-4">
                            <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
                                <i class="bi bi-people"></i>
                            </div>
                            <div class="ps-1">
                                <h6>&nbsp;&nbsp;&nbsp;{{cyber_criminals.count}}</h6>
                                <span class="text-muted small pt-2 ps-1">Cyber-Criminals</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Recent Sales -->
            <div class="col-12">
                <div class="card recent-sales overflow-auto">
                    <div class="card-body">
                        <div class="d-flex justify-content-between">
                            <h5 class="card-title">Criminal Profiles<span>| Recent</span></h5>
                            <a href="{% url 'profiler:criminal_profiles' %}">Show All</a>
                        </div>


                        <table class="table table-borderless" id="criminalsTable">
                            <thead>
                                <tr>
                                    <th scope="col">Name</th>
                                    <th scope="col">Classification</th>
                                    <th scope="col">Nationality</th>
                                    <th scope="col">Aggression Level</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for cyber_criminal in recent_cyber_criminals %}
                                <tr>
                                    <th scope="row">
                                        <a
                                            href="{% url 'profiler:view_profile' cyber_criminal.id %}">{{cyber_criminal.name}}</a>
                                    </th>
                                    <td>{{cyber_criminal.get_hacker_classification_display}}</td>
                                    <td>
                                        {{cyber_criminal.get_nationality_display}}
                                    </td>
                                    <td>{{cyber_criminal.aggression_level}}</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

{% block custom_js %}
<script>
    $('#criminalsTable').DataTable({
        dom: 'Bfrtip',
        buttons: [
            'copy', 'csv', 'excel', 'pdf', 'print'
        ]
    });
</script>
{% endblock custom_js %}